import { ContentsInGeneral } from '@src/interfaces-and-types/pages/settings';

export const contentsInGeneral: ContentsInGeneral[] = [
  {
    heading: 'Currency Conversion',
    subHeading: `A new version was made on ${new Date(Date.now())}.`,
    dropdown: [
      'USD - United States Dollar',
      'EUR - Euro',
      'JPY - Japanese Yen',
      'GBP - British Pound Sterling',
      'CAD - Canadian Dollar',
      'AUD - Australian Dollar',
      'CHF - Swiss Franc',
      'SEK - Swedish Krona',
      'NZD - New Zealand Dollar',
      'MXN - Mexican Peso',
      'SGD - Singapore Dollar',
      'HKD - Hong Kong Dollar',
      'NOK - Norwegian Krone',
      'KRW - South Korean Won',
      'TRY - Turkish Lira',
      'THB - Thai Baht',
      'BRL - Brazilian Real',
      'PHP - Philippine Peso',
      'IDR - Indonesian Rupiah',
      'MYR - Malaysian Ringgit',
      'ZAR - South African Rand',
      'INR - Indian Rupee',
      'CNY - Chinese Yuan',
      'DKK - Danish Krone',
      'PLN - Polish Zloty',
      'RUB - Russian Ruble',
      'HUF - Hungarian Forint',
      'ILS - Israeli New Shekel',
      'CLP - Chilean Peso',
      'ARS - Argentine Peso',
      'NGN - Nigerian Naira',
      'AED - United Arab Emirates Dirham',
      'BDT - Bangladeshi Taka',
      'BHD - Bahraini Dinar',
      'BMD - Bermudian Dollar',
      'CZK - Czech Koruna',
      'KWD - Kuwaiti Dinar',
      'LKR - Sri Lankan Rupee',
      'PKR - Pakistani Rupee',
      'SAR - Saudi Riyal',
      'TWD - New Taiwan Dollar',
      'UAH - Ukrainian Hryvnia',
      'VEF - Venezuelan Bolivar',
      'VND - Vietnamese Dong',
      'BTC - Bitcoin',
      'XAG - Silver',
      'XAU - Gold',
    ],
  },
  {
    heading: 'Primary Currency',
    subHeading:
      "Choose native to give the chain's native currency (such as HEDGE) precedence when showing values. To see values in your chosen fiat currency first, choose Fiat.",
    radio: {
      primary: true,
      fiat: false,
    },
  },
  {
    heading: 'Currency Language',
    subHeading: 'English',
    dropdown: ['English', 'Tamil', 'Telugu', 'Malayalam', 'Hindi', 'Chinese'],
  },
  {
    heading: 'Theme',
    subHeading: 'Select your favorite Hedge Hogg theme.',
    dropdown: ['Dark', 'Light', 'System'],
  },
];
